### ISSUE TITLE
1.06 files wont load 

### ISSUE THREAD

**Issue by WaschBaer0395** [WolvenKit/CyberCAT#24]
Error reading file: Object reference not set to an instance of an object

https://cdn.discordapp.com/attachments/789565732726767636/792624901554176000/Cyberpunk_2077.rar 

ManualSave 0 is from 1.05 
ManualSave 1 is from 1.06 ( exact same savegame just saved again in the 1.06 version ) 

manual save 0 loads, and 1 throws this error

**Comment by envy** [comment]
Either something is wrong with that save or with the node parser. My 1.06 saves load fine.

The node IDs are messed up when parsing:

![grafik](https://user-images.githubusercontent.com/241552/103175784-efb1b200-486c-11eb-93ed-e6c30910e627.png)

**Comment by WaschBaer0395** [comment]
well, the 1.05 version of that save loads fine, but when i save it in 1.06 again it wont load ,  ( all my 1.06 saves wont load with that same error ) , i also cant edit the 1.05 save since its quite a big leap behind my current 1.06 save file that i wanted to edit initially

**Comment by envy** [comment]
CSE can load the save, so there seems to be a bug inside CCATs parser.

You can try out https://github.com/PixelRick/CyberpunkSaveEditor in the meantime

**Comment by WaschBaer0395** [comment]
ye i already looked into it, i just dont know how to use it correctly ( i want to make some items dropable that arent , like the johnny clothing items etc ) , and maybe copy over a character skin from a newly created save that looks better in my opinion ( the arasaka editor corrupts the save file when i use it )

**Comment by SirBitesalot** [comment]
This should be fixed now
