### ISSUE TITLE
Cannot Load Patch 1.1 Save File - Throws Generic System Exception

### ISSUE THREAD

**Issue by Notheisz57** [WolvenKit/CyberCAT#49]
Exception is thrown when opening organic save game data from game version 1.1
Exception comes from a call stack ending at "GetInstanceFromName(string name)" method, line 249 in "GenericUnknownStructParser.cs" file, in the CyberCat.Core project.
Method is looking to create an instance of class type "Uint16", which is not found in the class list.

I was able to open and view a post-patch game save after making the following adjustments, but I have not tested any further functionality, such as saving the file or the subsequent loading of a modified save.

"GameItemID" class in "GameItemID.cs" needs an additional property:
`
        [RealName("uniqueCounter")]
        [RealType("Uint16")]
        public ushort uniqueCounter { get; set; }
`
Additional switch case statement to handle the Uint16 data, added to following two methods in the "GenericUnknownStructParser.cs" file:
 - ReadMappedFieldValue(BinaryReader reader, GenericUnknownStruct.BaseClassEntry cls, string fieldName, string fieldTypeName) - Line 506
 - ReadUnappedFieldValue(BinaryReader reader, string fieldName, string fieldType) - Line 590

Additional switch case:
`
                case "Uint16":
                    return reader.ReadUInt16();
`

I have not taken the time to fully understand the project, so I suspect it is more complicated than this.
Just putting the info out there in-case it is helpful.

If you need any more information from me, please let me know!

**Comment by seberoth** [comment]
Should be fixed in the next release
