### ISSUE TITLE
Update for 1.5

### ISSUE THREAD

**Issue by kasper-sh-hess** [WolvenKit/CyberCAT#56]
CyberCat wont work after update 1.5... shows 
errors occurred:(unkonwn type:"sslotvisulinfo")(unkonwn property:"uiscriptablesystem.dlcaddeditems")

**Comment by mikangogo** [comment]
@kasper-sh-hess 
I fixed that problem on #58

**Comment by abarb22** [comment]
I'm getting error message when trying to load save.  Message is...
Error reading file: One or more errors occurred. (Unknown type: "Data Buffer")

**Comment by jkerman2000** [comment]
I'm also getting the data buffer error.

**Comment by seberoth** [comment]
There isn't any update for 1.5 yet
